production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
staging:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
local:
  host: localhost
  database: db_name
  username: root
  password: 'root'